<a href="https://colab.research.google.com/github/zzeiadahmed/Data-Science-Projects/blob/main/Random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# For encoding categorical values
from sklearn.preprocessing import LabelEncoder

# For splitting data into train and test sets
from sklearn.model_selection import train_test_split

# For creating a decision tree model
from sklearn.tree import DecisionTreeClassifier

# For evaluating model performance
from sklearn.metrics import classification_report, confusion_matrix

# For visualizing the decision tree
from sklearn.tree import plot_tree

In [ ]:
df = sns.load_dataset('penguins')
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [ ]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum() #checking if there is null values

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [ ]:
df.sex.unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
pd.get_dummies(df['sex']).head()

Female   Male
0   False   True
1    True  False
2    True  False
4    True  False
5   False   True

In [ ]:
sex = pd.get_dummies(df['sex'], drop_first=True)
sex.head()

Male
0   True
1  False
2  False
4  False
5   True

In [ ]:
pd.get_dummies(df['island']).head()

Biscoe  Dream  Torgersen
0   False  False       True
1   False  False       True
2   False  False       True
4   False  False       True
5   False  False       True

In [ ]:
island = pd.get_dummies(df['island'], drop_first=True)
island.head()

Dream  Torgersen
0  False       True
1  False       True
2  False       True
4  False       True
5  False       True

In [ ]:
new_data = pd.concat([df,island,sex], axis=1)

In [ ]:
new_data.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   Dream  Torgersen   Male  
0  False       True   True  
1  False       True  False  
2  False       True  False  
4  False       True  False  
5  False       True   True

In [ ]:
new_data.drop(['island', 'sex'], axis=1, inplace=True)

In [ ]:
Y = new_data.species
Y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [ ]:
Y = Y.map({'Adelie':0, 'Chinstrap':1, 'Gentoo':2})
Y.head()

0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

In [ ]:
new_data.drop('species', axis=1, inplace=True)

In [ ]:
X=new_data
X.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Dream  \
0            39.1           18.7              181.0       3750.0  False   
1            39.5           17.4              186.0       3800.0  False   
2            40.3           18.0              195.0       3250.0  False   
4            36.7           19.3              193.0       3450.0  False   
5            39.3           20.6              190.0       3650.0  False   

   Torgersen   Male  
0       True   True  
1       True  False  
2       True  False  
4       True  False  
5       True   True

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=101)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(233, 7)
(100, 7)
(233,)
(100,)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators= 5, criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 2, 0, 0, 1, 2, 0, 2, 1, 0, 1, 0, 0, 0, 2, 0, 2, 0, 2, 0, 2, 2,
       0, 2, 0, 0, 1, 1, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 1, 2, 0, 2, 2, 0,
       0, 1, 0, 2, 1, 1, 2, 0, 1, 2, 0, 0, 0, 2, 1, 2, 0, 2, 1, 0, 0, 2,
       1, 2, 2, 1, 0, 2, 1, 1, 0, 2, 2, 0, 1, 0, 0, 1, 0, 0, 2, 0, 1, 2,
       2, 0, 2, 1, 0, 2, 2, 2, 0, 2, 0, 0])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))


[[40  0  0]
 [ 5 22  0]
 [ 0  0 33]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94        40
           1       1.00      0.81      0.90        27
           2       1.00      1.00      1.00        33

    accuracy                           0.95       100
   macro avg       0.96      0.94      0.95       100
weighted avg       0.96      0.95      0.95       100

0.95
